### ISSUE TITLE
django.db.utils.OperationalError: no such table: main.server_label__old

### ISSUE THREAD

**Issue by sagarkarnati** [chakki-works/doccano#51]
### System information
- **Linux Ubuntu 18.04**:
- **Python version :: 3.6.7**: 

### Describe the problem
Getting the attached exception when i try to install this in my local as per the steps
This exception i am getting when i try to annotate text.

### Source code / logs
[25/Dec/2018 04:35:39] "GET /static/images/favicons/favicon-32x32.png HTTP/1.1" 200 2379
Internal Server Error: /api/projects/1/docs/1/annotations/
Traceback (most recent call last):
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: main.server_label__old

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/rest_framework/generics.py", line 244, in post
    return self.create(request, *args, **kwargs)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/home/vidya/Documents/py_workspace/doccano/app/server/api.py", line 134, in perform_create
    serializer.save(document=doc, user=self.request.user)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/home/vidya/Documents/py_workspace/doccano/app/server/serializers.py", line 59, in create
    annotation = SequenceAnnotation.objects.create(**validated_data)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/models/query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/vidya/installs/anaconda3/envs/job-desc/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: main.server_label__old
[25/Dec/2018 04:35:46] "POST /api/projects/1/docs/1/annotations/ HTTP/1.1" 500 22875

**Comment by windranger747** [comment]
django 2.x confilt with sqlite 3.26.0，degrade sqlite to 3.25.3. django will fix it in next release.

**Comment by BrambleXu** [comment]
Just for someone who sees this issue later.
I can not reimplement this error with Django 2.1.2 and SQLite 3.26.0. 

As @windranger747 said, the new Django 2.1.4 version should solve this problem. So besides downgrading SQLite, you can also try to upgrade the Django to 2.1.4.

* [SQLite 3.26 breaks database migration ForeignKey constraint, leaving <table_name>__old in db schema](https://code.djangoproject.com/ticket/29182#comment:17)
* [Django 2.1.4 Fixed #29182](https://github.com/django/django/commit/c8ffdbe514b55ff5c9a2b8cb8bbdf2d3978c188f)

If this works, please give me feedback. I will update the Django version in requirements.txt

**Comment by pranaypratyush** [comment]
I am on sqlite 3.22.0-1ubuntu0.1 with django version 2.2.1 installed with conda. I am still getting this exact same error

**Comment by ferfigue** [comment]
Boa tarde 
Eu estava com o mesmo erro porem o makemigrations não esta lendo as modificaçoes no arquivo models.py. Pra resolver adicionei um novo item na tabela e rodei os comandos novamente 
(python manage.py makemigrations && python manage.py migrate) resolveu e todas as tabelas foram criadas normalmente.
